### ISSUE TITLE
Rule rebuild on plyara.utils.rebuild_yara_rule using external variable as a part of loop condition - bug

### ISSUE THREAD

**Issue by rakovskij-stanislav** [plyara/plyara#109]
Here is the case.

File `test.txt`:
```
test test test test test
```

rule:
```
rule sanity_check_external_variables {
    meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "22.08.2020"
    strings:
        $a = "test"
    condition:
        for count_of_test i in (1..#a) : ( @a[i] < 100 )
}
```

Sanity check using yara engine:
```
/testing_rules> yara d6.yar -d count_of_test=1 test.txt
sanity_check_external_variables test.txt
/testing_rules> yara d6.yar -d count_of_test=3 test.txt
sanity_check_external_variables test.txt
/testing_rules> yara d6.yar -d count_of_test=5 test.txt
sanity_check_external_variables test.txt
/testing_rules> yara d6.yar -d count_of_test=6 test.txt
```

Test case using plyara 2.1.1:
```
m = """rule sanity_check_external_variables {
    meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "22.08.2020"
    strings:
        $a = "test"
    condition:
        for count_of_test i in (1..#a) : ( @a[i] < 100 )
}
"""

parser = plyara.Plyara()
parser.parse_string(m)

y = plyara.utils.rebuild_yara_rule(parser.rules[0])
print(y)
```

Output:
```
rule sanity_check_external_variables
{
	meta:
		author = "Rakovskij Stanislav / disasm.me"
		date = "22.08.2020"

	strings:
		$a = "test"

	condition:
		for count_of_testi in (1..#a) : (@a[i]<100)
}
```

Expected condition: `for count_of_test i in (1..#a) : (@a[i]<100)`

I think the error is here - https://github.com/plyara/plyara/blob/master/plyara/utils.py#L470

To solve this problem you should check is this condition a part of `for ... ... in` block or not.

**Comment by utkonos** [comment]
@rakovskij-stanislav Thanks for the report. I'll get this fixed.

**Comment by utkonos** [comment]
@rakovskij-stanislav I severely dislike the `rebuild_yara_rule` function. It is basically impossible to maintain or improve. Plyara 3.0 will solve all rule rebuilding problems because it will be a real compiler rather than a kludge formatter like this function. I have no timeline for releasing 3.0, however.

That being said, what you have reported is a bug. The amount of code needed to do it right in all cases is just to much. However, I have fixed this particular bug with a simple fix. I have verified that the resulting yara rules are valid yara. There are now a few more spaces in the rebuilt output. I hope you're able to deal with that. This broke the unit test for `test_rebuild_yara_rule` but I adjusted that expected result to accomodate all the extra spaces. I also caught a typo in the test rule for that unit test (git blame: wasn't me!).

This should be an adequate bandaid until 3.0 is ready. Side note: if you would like to join the project and have time, let me know. Maybe you can tackle fixing this function properly. I don't use rule rebuilding, so I have no driver to spend the time on it.
