### ISSUE TITLE
Mistake with terms parsing in condition.

### ISSUE THREAD

**Issue by rakovskij-stanislav** [plyara/plyara#112]
Ruleset:
```yara
rule minus_bad{
	meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "22.08.2020"
        description = "test rule in which we have bad parsing of minus sign"
	strings:
	$str_after = "END_TAG"
        $str_before = "START_TAG"
	condition:
		 $str_before in (@str_after-512 .. @str_after)
}


rule minus_good{
	meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "22.08.2020"
        description = "test rule in which we have good parsing of minus sign"
	strings:
	$str_after = "END_TAG"
        $str_before = "START_TAG"
	condition:
		 $str_before in (@str_after - 512 .. @str_after)
}
```

Test file
```
START_TAG HELLO WORLD END_TAG
```

Test:
```python
> yara64.exe bug_parsing.yar bug_parsing.txt
minus_bad bug_parsing.txt
minus_good bug_parsing.txt


>python
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import plyara
>>> parser = plyara.Plyara()
>>> rules = parser.parse_string(open("bug_parsing.yar").read())
>>> rules[0]["condition_terms"]
['$str_before', 'in', '(', '@str_after-512', '..', '@str_after', ')'] #WRONG!
>>> rules[1]["condition_terms"]
['$str_before', 'in', '(', '@str_after', '-', '512', '..', '@str_after', ')'] #right
```

There is no problem with pluses:
Ruleset:
```yara
rule plus_pre_bad{
	meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "22.08.2020"
        description = "test rule in which we previously had bad parsing of minus sign"
	strings:
	$str_after = "END_TAG"
        $str_before = "START_TAG"
	condition:
		 $str_before in (@str_after+512 .. @str_after)
}


rule plus_pre_good{
	meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "22.08.2020"
        description = "test rule in which we have good parsing"
	strings:
	$str_after = "END_TAG"
        $str_before = "START_TAG"
	condition:
		 $str_before in (@str_after + 512 .. @str_after)
}
```
Test
```python
>>> parser = plyara.Plyara()
>>> rules = parser.parse_string(open("bug_parsing_2.yar").read())
>>> rules[0]["condition_terms"]
['$str_before', 'in', '(', '@str_after', '+', '512', '..', '@str_after', ')']
>>> rules[1]["condition_terms"]
['$str_before', 'in', '(', '@str_after', '+', '512', '..', '@str_after', ')']
>>>
```

**Comment by utkonos** [comment]
Thanks for the report. I'll get this fixed.

**Comment by utkonos** [comment]
@rakovskij-stanislav Unfortunately, I have not determined how to fix this. I think this has to do with what ply considers a word character. `-` should not be in the word character set and therefore would not end up in the token like it is here.

I tried one quick fix of using the latest (2022) version of PLY, but that did not fix the problem.

This will be fixed in 3.0 when the project is using SLY rather than PLY. Until then I have found one workaround: use YARA-X's `fmt` command to reformat the yara rule before using plyara. Then everything works as expected.

Also, if you want to take a crack at fixing this problem, please go ahead, PR would be very welcome.

**Comment by utkonos** [comment]
I did commit your test yara rule and file in the `tests/data` directory so it can be used in a unit test.

**Comment by utkonos** [comment]
I figured it out. These stringname regular expressions have a stray `-` in them which is an illegal character to have in a string name in yara. I will fix this tomorrow. Hopefully it can be changed without breaking anything else, but even if it does break something else, this is a bug.

https://github.com/plyara/plyara/blob/3c5e7cbf12b25446e7843a55c8fd479bfc06fc38/src/plyara/core.py#L753-L772
https://github.com/plyara/plyara/blob/3c5e7cbf12b25446e7843a55c8fd479bfc06fc38/src/plyara/core.py#L794-L799

```yara
rule illegal_stringname1
{
    strings:
        $-b = "test"
    condition:
        any of them
}

rule illegal_stringname2
{
    strings:
        $a-b = "test"
    condition:
        any of them
}

rule illegal_stringname3
{
    strings:
        $a- = "test"
    condition:
        any of them
}
```

```bash
% yara test.yar .
error: rule "illegal_stringname1" in test.yar(4): syntax error, unexpected '-', expecting '='
error: rule "illegal_stringname2" in test.yar(12): syntax error, unexpected '-', expecting '='
error: rule "illegal_stringname3" in test.yar(20): syntax error, unexpected '-', expecting '='
```

**Comment by utkonos** [comment]
This is an incomplete solution. It's almost correct, but there is still a bug due I think to precedence. Here is the output which is closer, but still incorrect.

```json
[
    {
        "condition_terms": [
            "$str_before",
            "in",
            "(",
            "@str_after",
            "-512",
            "..",
            "@str_after",
            ")"
        ],
        "metadata": [
            {
                "author": "Rakovskij Stanislav / disasm.me"
            },
            {
                "date": "22.08.2020"
            },
            {
                "description": "test rule in which we have bad parsing of minus sign"
            }
        ],
        "raw_condition": "condition:\n\t\t $str_before in (@str_after-512 .. @str_after)\n",
        "raw_meta": "meta:\n        author = \"Rakovskij Stanislav / disasm.me\"\n        date = \"22.08.2020\"\n        description = \"test rule in which we have bad parsing of minus sign\"\n\t",
        "raw_strings": "strings:\n\t$str_after = \"END_TAG\"\n        $str_before = \"START_TAG\"\n\t",
        "rule_name": "minus_bad",
        "start_line": 1,
        "stop_line": 11,
        "strings": [
            {
                "name": "$str_after",
                "type": "text",
                "value": "END_TAG"
            },
            {
                "name": "$str_before",
                "type": "text",
                "value": "START_TAG"
            }
        ]
    },
    {
        "condition_terms": [
            "$str_before",
            "in",
            "(",
            "@str_after",
            "-",
            "512",
            "..",
            "@str_after",
            ")"
        ],
        "metadata": [
            {
                "author": "Rakovskij Stanislav / disasm.me"
            },
            {
                "date": "22.08.2020"
            },
            {
                "description": "test rule in which we have good parsing of minus sign"
            }
        ],
        "raw_condition": "condition:\n\t\t $str_before in (@str_after - 512 .. @str_after)\n",
        "raw_meta": "meta:\n        author = \"Rakovskij Stanislav / disasm.me\"\n        date = \"22.08.2020\"\n        description = \"test rule in which we have good parsing of minus sign\"\n\t",
        "raw_strings": "strings:\n\t$str_after = \"END_TAG\"\n        $str_before = \"START_TAG\"\n\t",
        "rule_name": "minus_good",
        "start_line": 14,
        "stop_line": 24,
        "strings": [
            {
                "name": "$str_after",
                "type": "text",
                "value": "END_TAG"
            },
            {
                "name": "$str_before",
                "type": "text",
                "value": "START_TAG"
            }
        ]
    }
]
```

**Comment by utkonos** [comment]
I'm thinking about three ways to fix this. One problem is that many of the tokens that plyara uses are just inherited from the original version of plyara. They're tokens like `HYPHEN` which isn't correct. There should be `PLUS`, `MINUS`, etc so that token precedence rules can be used properly. There appears to be a precedence statement, but adding `HYPHEN` to this changes nothing.

https://github.com/plyara/plyara/blob/f3c6465d0a0bda99d0b0d3132e130f08a3519964/src/plyara/core.py#L819-L823

It is unclear from the PLY documentation whether this is even the correct syntax:

https://ply.readthedocs.io/en/latest/internals.html?highlight=precedence

PLY is no longer offered via PyPI. All the updates and changes since Feb 15, 2018 are only available in PLY's master branch in the main repo:
https://github.com/dabeaz/ply/commits/master/

SLY has a similar situation:
<img width="672" alt="image" src="https://github.com/user-attachments/assets/1a05cc4a-b351-46f1-bfb7-c5862d3863f1" />

I think the fastest fix is to vendor PLY or to make a fork under our org that keeps up with any changes. we can then make a release on pypi that can be installed. Or we can fully vendor it into this repo. At that point, we can cleanup the tokens so that they represent the correct tokens in YARA. And then we can implement the correct syntax for precedence of these new tokens.

Another alternative is to dig out what the syntax is for precedence now in the old version of PLY and see if `HYPHEN` can be handled properly now without breaking anything.

To make the jump to SLY, we would need to do the same thing: vendor it or adopt a fork.

**Comment by utkonos** [comment]
And there is the kludge fix: to check the resulting condition list for negative numbers which are not preceded by an appropriate operator. And under conditions where the operator is missing, the negative number can be assumed to be incorrectly parsed and is actually a `MINUS` (`HYPHEN`) and a `NUM`. This is actually the least effort, but increases tech debt.

**Comment by utkonos** [comment]
I may implement the kludge this week so that this bug can be fixed. And then add a new issue to get a fully correct fix implemented.

**Comment by utkonos** [comment]
Fixed it. The changes in token names is still needed, but not for fixing this bug. This one is totally fixed.
