### ISSUE TITLE
rebuild_yara_rule does not return rule comments

### ISSUE THREAD

**Issue by hxnoyd** [plyara/plyara#42]
Hi. The method rebuild_yara_rule() seems to be striping off rule comments.
For example, the following rule:
```
rule sample
{
    strings:
        $ = { 01 02 03 04 } // string 1
        $ = { 01 02 03 05 } // string 2
    condition:
        all of ($) // condition
}
```
Is correctly parsed (including comments):
```
[{'condition_terms': ['all', 'of', '(', '$', ')'], 'raw_strings': 'strings:\n        $ = { 01 02 03 04 } // string 1\n        $ = { 01 02 03 05 } // string 2\n    ', 'raw_condition': 'condition:\n        all of ($) // condition\n', 'comments': ['// condition', '// string 2', '// string 1'], 'rule_name': 'sample', 'stop_line': 8, 'start_line': 1, 'strings': [{'name': '$', 'value': '{ 01 02 03 04 }'}, {'name': '$', 'value': '{ 01 02 03 05 }'}]}]
```
But then rebuild_yara_rule() ignores comments:
```
rule sample {
        strings:
                $ = { 01 02 03 04 }
                $ = { 01 02 03 05 }
        condition:
                all of ($)
} 
```
Is this intentional? On the one hand this is not an issue if the rebuild rule is passed to yara for scanning. On the other hand, if you are rebuilding a rule for intel sharing, the rebuilder should preserve the rule comments.

Thanks in advance!
RD

**Comment by utkonos** [comment]
This is intentional. The comments key in the dictionary representation of the rule that plyara returns is just a list of comments. It doesn't return positional information, so the data for where to put them is not available during the rebuild process.

Line numbers are available during the parsing process, so this is definitely a do-able enhancement. It would break the schema of the resulting data, so it's a breaking change compatibility-wise.

This feature can be added as an option, or it can be added as a full feature with a new major version. I'll see what the other maintainers have to say.

**Comment by utkonos** [comment]
Oops. Closed by accident.

**Comment by rshipp** [comment]
It's definitely something I'd like to have, but I think putting the comments back would be difficult. 

* Single line comments can be on a line by themselves, or at the end of a line.
* Multiline comments can be either of the above, or in the middle of a line, so we'd need to track character offsets in addition to the line number.
* Line number is affected by both whitespace, and the comments themselves, so the original offset line number and the line number in the rebuilt rule are not guaranteed to match. Same with character offset.

Using `raw_condition` and `raw_strings` here instead makes comments in those sections easier, but comments between sections or in the `meta` would still have to be handled manually. I can't think of a good way to solve this.

**Comment by utkonos** [comment]
I can work on how to do this well. I'll include this work in the version I'm working on now.

**Comment by utkonos** [comment]
This feature is difficult as @rshipp said.

It may need the whole rebuild function being gutted and replaced with a templating engine like jinja2. This is the easier path, I think. But it will add a dependency to plyara. I would prefer coding it from scratch without a new dependency.

**Comment by utkonos** [comment]
I am including this in the features for 3.0.0. The rebuilt rules that are the output from the data model as of now use the YARA documentation as the style guide. Retaining the comments in the data model and in the JSON output is trivial. However, emitting the comments in the rebuilt YARA rules will be difficult for one reason. Because the rebuilt rules will be ideal rules according to the style guide, the number of lines in the strings or condition section may change between input and output. This is impossible to avoid. I think there should be an optional parameter that includes comments with best effort. We will need to make some decisions as to where a comment goes if the line number where it was located in the input no longer exists in the ideal rule output.

**Comment by jamie-34254** [comment]
It appears this is now implemented so I guess this should be closed as to not confuse new people?

**Comment by utkonos** [comment]
I've opened a separate issue for the change in 3.0
