### ISSUE TITLE
Rule imports pollution

### ISSUE THREAD

**Issue by hxnoyd** [plyara/plyara#53]
If Yara rule sets include module imports like "pe", these will be propagated to all rules in the set, regardless if used in the conditions.

Consider the following set:
```
rule sample_1
{
    strings:
        $s = "my_sample_string"
    condition:
        $s
}

import "pe"

rule sample_2
{
    condition:
        pe.number_of_resources > 1
}
```
After parsing, both rules will include the "pe" import, whereas it should be available only in the sample_2 rule.

Plyara version is 2.0.

Thanks in advance.

**Comment by rshipp** [comment]
Hi, thanks for the issue!

This is expected behavior, noted in the bottom of the [migration](https://github.com/plyara/plyara#migration) section here. It seems YARA's behavior is to only treat rules after the import statement as having access to that import. We could probably change plyara to do that as well - I believe the only reason we haven't done that so far is no one has asked for it. I'm not sure we can (or want to) set imports based on whether something is used in the conditions, as that might cause issues with custom definitions.

As a workaround, you can define a new `Plyara` object for each rule, like this:

```python
for rule in rules:
    parser = plyara.Plyara()
    parsed_rule = parser.parse_string(rule)
```

That means you'd have to either have one rule per file, or split up your rule files into individual rules with regex before parsing.

All that said, is the after-import behavior something you think would be valuable for us to implement? It's not something I can make use of myself, but if it makes your workflow easier it's worth doing IMO.

**Comment by hxnoyd** [comment]
Hi,

My main use case for plyara is to extract yara rules from large rule sets (one file), usually collections of independent rules, without any scopes/variable definitions. Therefore, I expect that parsed rules do not include artifacts. 

For the sake of simplicity, I would prefer plyara to treat rules individually.

Module names are already hardcoded in plyara (IMPORT_OPTIONS), hence imports could be derived out of conditions when parsing the rule.

**Comment by utkonos** [comment]
@hxnoyd I agree it would be better if rules didn't include artifacts. Keeping track of imports per rule based on position in the ruleset is ideal. If you have a proposed way to do this, can you submit a PR with the proposed code change?

**Comment by rshipp** [comment]
OK, I talked with someone who knows more about YARA than me, and I have some clarifications here. I think the **condition-imports** behavior you're asking for is possible, I'm just not sure if we want to do that, since it's different from how YARA treats imports.

From what I understand, in your workflow, the **after-import** behavior YARA uses still won't give you the output you expect. For input like this:

```yara
rule sample_1
{
    strings:
        $s = "my_sample_string"
    condition:
        $s
}

import "pe"

rule sample_2
{
    condition:
        pe.number_of_resources > 1
}

rule sample_3
{
    strings:
        $s = "my_sample_string"
    condition:
        $s
}
```

YARA treats the third rule as having a "pe" import, even though it's never used.

In practice, we can safely assume that any import not used in the conditions is not needed, and remove it. So the question comes down to this: do we want to remove all "unused" imports from parsed rule objects, even though that's different than what YARA does? Or do we want to follow YARA's behavior and include any import that is declared before the rule?

**Comment by utkonos** [comment]
The way the code works now is to apply all found imports to each rule parsed in one file. I agree that this is sub-optimal. I'm working on a patch that will only apply imports to rules **after** the import is found. I will look into includes since this is also handled in the same way. I am not sure we need to treat includes in this way, but I will look.

Whether a rule **uses** an import is not relevant, in my opinion. The import needs to be shown as applying to a particular rule.

1. Imports are applied to rules earlier in the ruleset where that import is not actually available for use in a rule. <- Bug
2. Imports are applied to rules after the import, but the import is not used in the rule. <- Not a bug, no change needed

**Comment by hxnoyd** [comment]
@rshipp and @utkonos, while I understand the YARA engine comparison, I still don't see the reason why plyara needs to behave in the same way. In the end, rebuild_yara_rule() will rebuild individually and what once was a rule set with a single **import "pe"** (somewhere in the data set), will result in a rule set with multiple imports for the same module... why do we need the repetition?

IMHO, I think that imports are the least of problems when dealing with complex Yara rule sets. Questions like scope and external variables handling concerns me a lot more. Anyway, even for these cases, I still prefer to deal with rules individually and handle the rule relations (global, private) on my end, outside of plyara.

I've been playing with parse_string() and drafted a poc that generates imports out of conditions:
```
    def parse_string(self, input_string):
        """Take a string input expected to consist of YARA rules, and return list of dictionaries representing them.

        Args:
            input_string: String input expected to consist of YARA rules.

        Returns:
            dict: All the parsed components of a YARA rule.
        """
        self._raw_input = input_string
        yacc.parse(input_string)

        for rule in self.rules:
            imports = []
            for term in rule['condition_terms']:
                if term.split('.')[0] in self.IMPORT_OPTIONS and term.split('.')[0] not in imports:
                    imports.append(term.split('.')[0])
            rule['imports'] = imports
            if any(self.includes):
                rule['includes'] = self.includes
```

**Comment by utkonos** [comment]
@hxnoyd I have a potential solution, but it will change the output format drastically. Rather than including imports in the rule key,value pair, we can make an outer hierarchy of imports and then rules under the imports. The import would not show up in the rule JSON. You can happily ignore the ones that are not used in a rule, and the imports will appear in the correct position in the hierarchy as they're correctly applied in YARA.

Does this work?
import
   rule
   rule
   rule
import
import
   rule
   rule
   rule

**Comment by hxnoyd** [comment]
@utkonos to be honest, changing to a nested rule format, at least in my case, would do more harm than good. Moreover, I would still need to come up with some logic to decide when to keep the imports, which is not much different from the term based approach. That said, please don't change the current rule format 🙏 .

I understand that this is a difficult topic to tackle, due to the flexibility of rule sets. Maybe I can workaround with rule post-processing (dropping unneeded imports).

**Comment by utkonos** [comment]
No changes yet. Just proposing an idea.

**Comment by rshipp** [comment]
@hxnoyd If it helps at all, I could maybe improve [the YARA regex in this other library](https://github.com/InQuest/python-iocextract/blob/master/iocextract.py#L210) to catch imports/includes, and you could use that to separate out your rules before then passing them to plyara? Then you wouldn't have to postprocess anything.

**Comment by hxnoyd** [comment]
@rshipp, that sounds like a good idea 👍

**Comment by rshipp** [comment]
Alright, I'm waiting for an internal review but if you want to test this out in the meantime:

```
pip install git+https://github.com/InQuest/python-iocextract@issue/27-yara-regex
```

And you should be able to do something like this:

```python
import iocextract
import plyara

parsed_rules = []
for rule in iocextract.extract_yara_rules(MY_RULES_STRING):
    parser = plyara.Plyara()
    parsed_rules.append(parser.parse_string(rule))
```

Let me know how it goes. The regex won't work in all cases, but hopefully its good enough to not choke on your input set.

**Comment by rshipp** [comment]
I've pushed the `iocextract` changes to PyPI, hope it's helpful.

As for the rest of this issue, I'm inclined to agree with @utkonos that we should follow YARA's behavior and have imports attached to all rules after the import. My reasoning is, it's possible we could get better results for imports by looking at the conditions, but we could never do includes that way, and I think it's better to follow "principle of least surprise" here than implement different logic just for imports.

**Comment by hxnoyd** [comment]
@rshipp: the iocextract rule splitting worker on my rule sets. I'm going to test some more sets, and it all goes well I'll use it to workaround this behaviour.

Thanks for the follow up!

**Comment by utkonos** [comment]
I have a decent solution. I have added a parameter called `import_effects` which allows users to get an idea of the import effects as we have discussed above. It also allows for new behavior added by @cccs-rs to remove imports from rules that do not use them.
