### ISSUE TITLE
Consider using conditional lexing

### ISSUE THREAD

**Issue by rshipp** [plyara/plyara#6]
As per the comment here: https://github.com/plyara/plyara/pull/2#issuecomment-394844704. Link with more information here: http://www.dabeaz.com/ply/ply.html#ply_nn21. 

This may give us some improvements with a small maintainability tradeoff. If anyone has any opinion feel free to comment. Otherwise I'll look into this as time allows.

**Comment by Taskr** [comment]
The primary use case that I have had for conditional lexing is parsing byte strings. By entering an exclusive lexing state, I can use more simple regexes to parse out the byte string. I can also catch errors that would otherwise be accepted with a large regex.

**Example:** the byte jump section in the original byte string [regex](https://github.com/plyara/plyara/blob/master/plyara.py#L711) will accept any number range for the jump; this includes cases where the first number value is smaller than the second (which is not valid). 

A simpler regex can be used with an exclusive lexing state to capture the two numbers in the jump range and subsequently compared for validity, as seen [here](https://github.com/PUNCH-Cyber/YaraGuardian/blob/master/plyara/plyara/plyara.py#L721-L728).

**Comment by rshipp** [comment]
Tagging @plyara/all for any input. If no one opposes this, I'll merge these changes (https://github.com/PUNCH-Cyber/YaraGuardian/commit/fe8641aaa8490fd9a316c2dce69e5270a6d9470f, https://github.com/PUNCH-Cyber/YaraGuardian/commit/ffdf04f080df5fe9436f8f68546a4932860c8cec) with our slightly updated bytestring regex and put that in master along with some extra test cases.

**Comment by rshipp** [comment]
@Taskr merged in eb6cbff. Feel free to review the changes.

**Comment by Taskr** [comment]
Looks great! Thanks @rshipp
