### ISSUE TITLE
New xor modifier causes parsing failure

### ISSUE THREAD

**Issue by edeca** [plyara/plyara#64]
Version 3.11 of Yara brings a more flexible `xor` modifier ([see changelog](https://github.com/VirusTotal/yara/releases/tag/v3.11.0)).

This means that for versions above 3.11 the `xor` modifier can also be written like `xor(0x01-0xff)` to restrict the range.

A simple rule that fails to parse is:

    rule xor_test {
        strings:
            $ = "test test test" xor(0x01-0x02)
        condition:
            any of them
    }

It's possible this rule breaks the internal state of the parser, because subsequent rules do not seem to correctly parse.  However, I have not verified this yet.

**Comment by utkonos** [comment]
Thanks for the report! We'll get an update for this and any other changes with recent YARA versions shortly.

**Comment by utkonos** [comment]
I'm not sure of an easy change to support this new format for xor string operator. This change requires rewriting how string operators are parsed.

**Comment by malwarefrank** [comment]
I am not an expert in lexers and parsers, so this may be wrong, but give this a try: https://github.com/malwarefrank/plyara/commit/42a9ead34168b4253a78f070bfc4d7874ec994d6

If that works, then I can create a test and submit a PR

**Comment by malvidin** [comment]
All of the following are all legitimate XOR modifiers. The first is already handled, and the next one appears to be handled by @malwarefrank's modification. 
```
xor
xor(0x01-0xFA)

xor(0x01)
xor(1)
xor(1-250)
xor(000001-00000250)
```
This requires all of the following, unless the xor_mod is created as a new token.  I didn't see a way to create a single byte hex/int token that didn't cause extraction issues with the NUM and HEXNUM tokens.
```
                           | XOR_MOD LPAREN NUM RPAREN
                           | XOR_MOD LPAREN NUM HYPHEN NUM RPAREN
                           | XOR_MOD LPAREN HEXNUM RPAREN
                           | XOR_MOD LPAREN HEXNUM HYPHEN HEXNUM RPAREN
                           | XOR_MOD LPAREN NUM HYPHEN HEXNUM RPAREN
                           | XOR_MOD LPAREN HEXNUM HYPHEN NUM RPAREN
```

I recommend adding a way to determine which version of YARA that plyara can parse, so that accepting the modified XOR won't impact use with versions before YARA 3.11.0.

I did not add anything yet to `rebuild_yara_rule` to recreate string modifiers with parameters, or checks for YARA >= 3.11.0 version compatibility.

**Comment by malvidin** [comment]
I've made additional modifications here https://github.com/malvidin/plyara/commit/35b9b5da2e93e087e3b282e23c3379b302fcdb72
, but there are still enhancements that could be made.

@malwarefrank, does my current commit meet your current needs?

- Recommend imports being made before use
- Ensure all named and anonymous strings are referenced
- Parse conditions in a way that ensures logical validity
- Version compatibility checks for conditions & iteration

The reason I brought back the `rebuild_yara_rule` utility is due to the use by CCCS-Yara 
https://github.com/CybercentreCanada/CCCS-Yara/blob/master/yara-validator/yara_validator.py#L414

**Comment by tlansec** [comment]
Hi,

I'd just like to add a ++ for considerations on _rebuild_yara_rule_ i think most plyara users will want to rebuild a rule from the parsed rule (otherwise why not just check it compiles with yara itself?).

Thanks,
Tom
